version: '3.1'

services:

   rabbitmq:
    image: rabbitmq:3.7.18-management
    container_name: cqrs-rabbitmq
    volumes:
      - ${CONFIG_PATH_HOST}/rabbitmq/definition.json:/etc/rabbitmq/definition.json
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definition.json"
    expose:
      - 5672
      - 15672
    ports:
      - 15672:15672
      - 5672:5672
